### ISSUE TITLE
somehow doesn't work

### ISSUE THREAD

**Issue by arm2arm** [edupooch/nodestat#3]
on slurm 22 05.11 it doesnot work:
```
nodestat
PARTITION      NODE           CPUS        GPUS      MEM (G)           
Traceback (most recent call last):
  File "/usr/local/bin/nodestat", line 11, in <module>
    load_entry_point('nodestat==0.12', 'console_scripts', 'nodestat')()
  File "/usr/local/lib/python3.6/site-packages/nodestat.py", line 153, in main
    partitions = set([info['partition'] for node_name, info in node_info.items()])
  File "/usr/local/lib/python3.6/site-packages/nodestat.py", line 153, in <listcomp>
    partitions = set([info['partition'] for node_name, info in node_info.items()])
KeyError: 'partition'
[nnewl1:~]#nodestat -j
Traceback (most recent call last):
  File "/usr/local/bin/nodestat", line 11, in <module>
    load_entry_point('nodestat==0.12', 'console_scripts', 'nodestat')()
  File "/usr/local/lib/python3.6/site-packages/nodestat.py", line 144, in main
    job_info = get_slurm_jobs()
  File "/usr/local/lib/python3.6/site-packages/nodestat.py", line 78, in get_slurm_jobs
    tres_str = job.split('AllocTRES=')[1].split(' ')[0]
IndexError: list index out of range
```

**Comment by canoalberto** [comment]
To fix it you need #1 for sure, and maybe #2 depending on how your nodes are listed
